"""like

Revision ID: 20d49acfe6a3
Revises: 115e93588e6d
Create Date: 2020-08-19 04:02:01.471515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20d49acfe6a3'
down_revision = '115e93588e6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_like_created_at'), 'like', ['created_at'], unique=False)
    op.create_index(op.f('ix_like_updated_at'), 'like', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_like_updated_at'), table_name='like')
    op.drop_index(op.f('ix_like_created_at'), table_name='like')
    op.drop_table('like')
    # ### end Alembic commands ###
