"""post update

Revision ID: 84fa9da69466
Revises: a4605d83fb34
Create Date: 2020-08-18 22:45:44.269725

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '84fa9da69466'
down_revision = 'a4605d83fb34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_post_updated_at', table_name='post')
    op.drop_column('post', 'title')
    op.drop_column('post', 'updated_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('updated_at', mysql.DATETIME(), nullable=True))
    op.add_column('post', sa.Column('title', mysql.VARCHAR(collation='utf8_czech_ci', length=20), nullable=True))
    op.create_index('ix_post_updated_at', 'post', ['updated_at'], unique=False)
    # ### end Alembic commands ###
