"""post update

Revision ID: a44ae8116168
Revises: 84fa9da69466
Create Date: 2020-08-18 23:21:05.173028

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a44ae8116168'
down_revision = '84fa9da69466'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('content', mysql.TEXT(collation='utf8_czech_ci'), nullable=True))
    # ### end Alembic commands ###
