"""posts table

Revision ID: a4605d83fb34
Revises: 101440bad58d
Create Date: 2020-08-18 07:20:25.709143

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a4605d83fb34'
down_revision = '101440bad58d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('content', sa.Text(), nullable=True))
    op.add_column('post', sa.Column('posted_at', sa.DateTime(), nullable=True))
    op.add_column('post', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_post_posted_at'), 'post', ['posted_at'], unique=False)
    op.create_index(op.f('ix_post_updated_at'), 'post', ['updated_at'], unique=False)
    op.drop_index('ix_post_timestamp', table_name='post')
    op.drop_column('post', 'body')
    op.drop_column('post', 'timestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('timestamp', mysql.DATETIME(), nullable=True))
    op.add_column('post', sa.Column('body', mysql.VARCHAR(collation='utf8_czech_ci', length=140), nullable=True))
    op.create_index('ix_post_timestamp', 'post', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_post_updated_at'), table_name='post')
    op.drop_index(op.f('ix_post_posted_at'), table_name='post')
    op.drop_column('post', 'updated_at')
    op.drop_column('post', 'posted_at')
    op.drop_column('post', 'content')
    # ### end Alembic commands ###
