"""like

Revision ID: a749364d183b
Revises: eda411aace97
Create Date: 2020-08-25 07:03:26.089247

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a749364d183b'
down_revision = 'eda411aace97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('like', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('like', sa.Column('post', sa.Integer(), nullable=False))
    op.add_column('like', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('like', sa.Column('user', sa.Integer(), nullable=False))
    op.drop_constraint('like_ibfk_1', 'like', type_='foreignkey')
    op.drop_constraint('like_ibfk_2', 'like', type_='foreignkey')
    op.create_foreign_key(None, 'like', 'post', ['post'], ['id'])
    op.create_foreign_key(None, 'like', 'user', ['user'], ['id'])
    op.drop_column('like', 'user_id')
    op.drop_column('like', 'post_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('like', sa.Column('post_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('like', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'like', type_='foreignkey')
    op.drop_constraint(None, 'like', type_='foreignkey')
    op.create_foreign_key('like_ibfk_2', 'like', 'user', ['user_id'], ['id'])
    op.create_foreign_key('like_ibfk_1', 'like', 'post', ['post_id'], ['id'])
    op.drop_column('like', 'user')
    op.drop_column('like', 'updated_at')
    op.drop_column('like', 'post')
    op.drop_column('like', 'created_at')
    # ### end Alembic commands ###
